### ISSUE TITLE
Descrição do hackdisrupt na página inicial

### ISSUE THREAD

**Issue by mblodorn** [bukinoshita/hackdisrupt#47]
Na página inicial do hackdisrupt existe uma breve listagem do que a ferramenta oferece:

"aprenda / ensine / forum / trampos / podcasts"

Porém as palavras "aprenda" e "ensine" acabam ficando desconexas com os outros tópicos. Penso que ficaria mais agradável com tudo listado no infinitivo:

"aprender / ensinar / forum / trampos / podcasts"

O que acham?

O texto está localizado neste arquivo:
https://github.com/bukinoshita/hackdisrupt/blob/c8e9dc8da45f0041878bca3dd60842638ca64507/components/home-main.js

**Comment by bukinoshita** [comment]
Boa @mblodorn! Concodo
