### ISSUE TITLE
Mensagem de confirmação não é exibida após cadastro no beta

### ISSUE THREAD

**Issue by mblodorn** [bukinoshita/hackdisrupt#51]
Após autorizar a autenticação pelo github para inscrição no beta recebi a mensagem:
'Esse `id` não existe, mas você pode entrar na nossa lista beta sua coisa linda!'

Isso está correto?

Link do arquivo com a mensagem:

https://github.com/bukinoshita/hackdisrupt/blob/master/pages/success.js

**Comment by bukinoshita** [comment]
Eu tinha feito umas mudanças que afetou isso... tem como você tentar de novo e ver se a messagem ainda ocorre?

**Comment by mblodorn** [comment]
@bukinoshita criei uma conta nova para fazer o teste, mas mesmo  quando estou logado na conta nova aparece a mensagem "> você já está na lista. obrigado por fazer parte! acompanhe a gente no github." no site e não consigo me cadastrar de novo. Tenho certeza que não cadastrei a conta pois acabou de ser criada. O nome é @testson154 (não julgue).

**Comment by bukinoshita** [comment]
É porque no site você ainda está `logado` com a sua outra conta... a gente não tem `logout` ainda. Quando você se cadastra a gente salve um `cookies` com seu id

**Comment by mblodorn** [comment]
Vou aguardar a resolução do #53 para testar novamente

**Comment by mblodorn** [comment]
Testei novamente após o release v0.0.2 e está funcionando normalmente agora.

**Comment by bukinoshita** [comment]
nice, valeu @mblodorn !
